#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for docs-to-markdown

set -e

echo "========================================"
echo "Starting Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "pyproject.toml" ]; then
    echo -e "${RED}Error: pyproject.toml not found. Please run this script from the project root.${NC}"
    exit 1
fi

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python
if ! command -v python3 &> /dev/null; then
    if ! command -v python &> /dev/null; then
        echo -e "${RED}Error: Python 3.9+ is not installed or not in PATH${NC}"
        echo "Please install Python 3.9 or higher from https://www.python.org/downloads/"
        exit 1
    else
        PYTHON_CMD="python"
    fi
else
    PYTHON_CMD="python3"
fi

echo -e "${GREEN}✓ Python found: $(${PYTHON_CMD} --version)${NC}"

# ============================================
# CREATE VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo "Setting up virtual environment..."

if [ -d ".venv" ]; then
    echo -e "${YELLOW}Virtual environment already exists. Skipping creation.${NC}"
else
    echo "Creating virtual environment..."
    ${PYTHON_CMD} -m venv .venv
    echo -e "${GREEN}✓ Virtual environment created${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Activate virtual environment
source .venv/bin/activate

# Upgrade pip
echo "Upgrading pip..."
pip install --upgrade pip -q

# Install dependencies
echo "Installing package dependencies..."
pip install -r requirements.txt -q

# Install package in editable mode
echo "Installing docs-to-markdown in editable mode..."
pip install -e . -q

echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# VERIFY INSTALLATION
# ============================================

echo ""
echo "Verifying installation..."

if command -v docs-to-markdown &> /dev/null; then
    echo -e "${GREEN}✓ docs-to-markdown command available${NC}"
else
    echo -e "${RED}✗ docs-to-markdown command not found${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Virtual environment: .venv/"
echo "Python: $(${PYTHON_CMD} --version)"
echo ""
echo "To activate the virtual environment:"
echo "  source .venv/bin/activate"
echo ""
echo "To run the application:"
echo "  docs-to-markdown <input_dir> <output_dir>"
echo ""
echo "To run tests:"
echo "  pytest"
echo ""
echo "For more information, see README.md"
echo ""
